### ISSUE TITLE
Add left icons for menu 

### ISSUE THREAD

**Issue by burymm** [irina-tsedryk/JS#1]
You need icons for left menu and hover

**Comment by irina-tsedryk** [comment]
@burymm  How do I move the text to the icon? 
If I do left aligned, the text the text over icons

**Comment by irina-tsedryk** [comment]
@burymm please review  Task-1-3-4-5 (#7)  branch-1-3-4-5-task

**Comment by irina-tsedryk** [comment]
I solved the problem

**Comment by burymm** [comment]
Looks good. But you have to large gap between icon and text. Gap should be 10 px. And text should align to left side as in mockup.

**Comment by irina-tsedryk** [comment]
@burymm please review branch-1-task

**Comment by burymm** [comment]
I suppose for this task you should remove your js code. It's not for this issue.

**Comment by irina-tsedryk** [comment]
@burymm  This attempt at writing. I removed the unnecessary branch

**Comment by burymm** [comment]
Closed as resolve
