### ISSUE TITLE
Update css

### ISSUE THREAD

**Issue by burymm** [irina-tsedryk/JS#12]
I reviewed your styles more details. 
1) You should use side for block. It's bad practice use padding on top for block. Because if you will need remove block that on top  your block block don't move on top. It will be on it place. https://www.screencast.com/t/vEIJ9lgxLWc I suppose it will help to your. 
2) The same for middle box https://www.screencast.com/t/vEIJ9lgxLWc. You can hover you mouse on block on html code that right on your page and see it size.

**Comment by irina-tsedryk** [comment]
@burymm please review branch-12. 
I added positioning. Do I undestand you correctly?

**Comment by burymm** [comment]
In general. We will fix another in future by small fixes.
