### ISSUE TITLE
Use css gradient instead of image on menu background

### ISSUE THREAD

**Issue by burymm** [irina-tsedryk/JS#2]
If you don't need support old version of browsers please use css gradient instead of image. 

This can help you. http://www.colorzilla.com/gradient-editor/

**Comment by burymm** [comment]
You should add white border on top
https://www.screencast.com/t/1blwkJE1MZ0J
I send to you pictures that you can use in colorzilla

**Comment by irina-tsedryk** [comment]
@burymm please review Branch 2 task border on top

**Comment by burymm** [comment]
0) You still use image for gradients. You should use css gradint.  https://www.screencast.com/t/DD1ep9tA
1) You should add padding to bootom for hover effect on menu.  It should have not space on bottom as on image that I provided https://www.screencast.com/t/zzEoXCu6j
2) You should remove shadow effect from text on hover effect.

**Comment by irina-tsedryk** [comment]
@burymm please review Branch 2
![view](https://cloud.githubusercontent.com/assets/24461366/22300405/675af8a0-e338-11e6-97d3-3e67315debe0.png)

I corrected your comments. 
Thank you:)
