### ISSUE TITLE
Hover effect on main menu

### ISSUE THREAD

**Issue by burymm** [irina-tsedryk/JS#3]
Please add hover effect to hover menu. Use css gradient for background.

**Comment by irina-tsedryk** [comment]
@burymm please review  Task-1-3-4-5 (#7)  branch-1-3-4-5-task

**Comment by burymm** [comment]
Looks good. But you have to large gap between icon and text. Gap should be 10 px. And text should align to left side as in mockup.

**Comment by burymm** [comment]
I send to you images. Hover effect should have gradient

**Comment by irina-tsedryk** [comment]
@burymm please review Branch-3-task-hover-effect

**Comment by irina-tsedryk** [comment]
@burymm thank you for sending gradients. It helped me a lot

**Comment by burymm** [comment]
You should use it on http://www.colorzilla.com/gradient-editor/ this site to generate css. https://www.screencast.com/t/RlanoSFjswFL

**Comment by irina-tsedryk** [comment]
@burymm thank you. Now I understand. I corrected the your comments.  They are in branch 2

**Comment by burymm** [comment]
Looks good.
