### ISSUE TITLE
Email should be "clickable"

### ISSUE THREAD

**Issue by burymm** [irina-tsedryk/JS#4]
On footer you have contact email. As user I want to click and open apllication for email by default. 
Please read http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto
You need style this link it should the same property like text, but if user hover over link he should see finger.
http://htmlbook.ru/css/cursor

**Comment by irina-tsedryk** [comment]
@burymm please review  Task-1-3-4-5 (#7)  branch-1-3-4-5-task
